### ISSUE TITLE
Lack of "SDL_JoystickHasRumble" and "SDL_JoystickHasRumbleTriggers" function imports

### ISSUE THREAD

**Issue by furious-programming** [PascalGameDevelopment/SDL2-for-Pascal#45]
Headers does not contain imports of the following functions:

* **[SDL_JoystickHasRumble](https://wiki.libsdl.org/SDL_JoystickHasRumble)**
* **[SDL_JoystickHasRumbleTriggers](https://wiki.libsdl.org/SDL_JoystickHasRumbleTriggers)**

The following imports works on Windows 10, using `SDL 2.0.20.0` dll file:

```pascal
function SDL_JoystickHasRumble(joystick: PSDL_Joystick): TSDL_Bool; cdecl;
  external SDL_LibName {$IFDEF DELPHI} {$IFDEF MACOS} name '_SDL_JoystickHasRumble' {$ENDIF} {$ENDIF};

function SDL_JoystickHasRumbleTriggers(joystick: PSDL_Joystick): TSDL_Bool; cdecl;
  external SDL_LibName {$IFDEF DELPHI} {$IFDEF MACOS} name '_SDL_JoystickHasRumbleTriggers' {$ENDIF} {$ENDIF};
```

You should check if those are proper for other platforms.

**Comment by Free-Pascal-meets-SDL-Website** [comment]
Thanks for the patch! If this works in Win10 I don't see a reason for it not to work on other platforms.

According to our code style guidelines it is preferable to use native Boolean instead of TSDL_Bool, but it will be acceptable for now. The difference has to be examined in more detail. (See #30)
